/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Saul
 */
public class FrmArticulos extends javax.swing.JFrame {

    /**
     * Creates new form FrmArticulos
     */
    public FrmArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpAsociados = new javax.swing.JTabbedPane();
        pnlAnexos = new javax.swing.JPanel();
        etCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        etCodigoInterno = new javax.swing.JLabel();
        txtCodigoInterno = new javax.swing.JTextField();
        etDescripcionNormal = new javax.swing.JLabel();
        txtDescripcionNormal = new javax.swing.JTextField();
        etDescripcionCorta = new javax.swing.JLabel();
        txtDescripcionCorta = new javax.swing.JTextField();
        etProveedor = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox();
        cmbDepartamento = new javax.swing.JComboBox();
        etDepartamento = new javax.swing.JLabel();
        cmbLinea = new javax.swing.JComboBox();
        etProveedor2 = new javax.swing.JLabel();
        etSubCategoria = new javax.swing.JLabel();
        etLinea = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox();
        cmbSubCategoria = new javax.swing.JComboBox();
        etUnidad = new javax.swing.JLabel();
        cmbUnidad = new javax.swing.JComboBox();
        etCategoria = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        spnStock = new javax.swing.JSpinner();
        etStock = new javax.swing.JLabel();
        spnStockMinimo = new javax.swing.JSpinner();
        etStockMinimo = new javax.swing.JLabel();
        spnStockMaximo = new javax.swing.JSpinner();
        etStockMaximo = new javax.swing.JLabel();
        etCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        txtUtilidad = new javax.swing.JTextField();
        etUtilidad = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        etIVA = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        etPrecioVenta = new javax.swing.JLabel();
        btnGuardarArticulo = new javax.swing.JButton();
        chbIVA = new javax.swing.JCheckBox();
        pnlAsociados = new javax.swing.JPanel();
        etCodigoBarras1 = new javax.swing.JLabel();
        txtCodigoBarras1 = new javax.swing.JTextField();
        etCodigoInterno1 = new javax.swing.JLabel();
        txtCodigoInterno1 = new javax.swing.JTextField();
        etDescripcionNormal1 = new javax.swing.JLabel();
        txtDescripcionNormal1 = new javax.swing.JTextField();
        txtDescripcionCorta1 = new javax.swing.JTextField();
        etDescripcionCorta1 = new javax.swing.JLabel();
        etUnidad1 = new javax.swing.JLabel();
        cmbUnidad1 = new javax.swing.JComboBox();
        etCosto1 = new javax.swing.JLabel();
        txtCosto1 = new javax.swing.JTextField();
        etProveedor3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        etUtilidad1 = new javax.swing.JLabel();
        txtUtilidad1 = new javax.swing.JTextField();
        etPrecioVenta1 = new javax.swing.JLabel();
        txtPrecioVenta1 = new javax.swing.JTextField();
        btnGuardarArticulo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulosDesign = new javax.swing.JTable();
        etTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAnexos.setLayout(null);

        etCodigoBarras.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etCodigoBarras.setText("Código de barras:");
        pnlAnexos.add(etCodigoBarras);
        etCodigoBarras.setBounds(10, 11, 112, 15);

        txtCodigoBarras.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtCodigoBarras);
        txtCodigoBarras.setBounds(10, 32, 231, 30);

        etCodigoInterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etCodigoInterno.setText("Código Interno");
        pnlAnexos.add(etCodigoInterno);
        etCodigoInterno.setBounds(272, 11, 100, 15);

        txtCodigoInterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtCodigoInterno);
        txtCodigoInterno.setBounds(270, 30, 170, 30);

        etDescripcionNormal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etDescripcionNormal.setText("Descripción normal:");
        pnlAnexos.add(etDescripcionNormal);
        etDescripcionNormal.setBounds(480, 10, 124, 15);

        txtDescripcionNormal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtDescripcionNormal);
        txtDescripcionNormal.setBounds(480, 30, 440, 30);

        etDescripcionCorta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etDescripcionCorta.setText("Descripción corta:");
        pnlAnexos.add(etDescripcionCorta);
        etDescripcionCorta.setBounds(10, 71, 114, 15);

        txtDescripcionCorta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtDescripcionCorta);
        txtDescripcionCorta.setBounds(10, 92, 430, 30);

        etProveedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etProveedor.setText("Proveedor:");
        pnlAnexos.add(etProveedor);
        etProveedor.setBounds(480, 70, 68, 15);

        cmbProveedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(cmbProveedor);
        cmbProveedor.setBounds(480, 90, 440, 30);

        cmbDepartamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(cmbDepartamento);
        cmbDepartamento.setBounds(10, 152, 201, 30);

        etDepartamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etDepartamento.setText("Departamento:");
        pnlAnexos.add(etDepartamento);
        etDepartamento.setBounds(10, 131, 100, 15);

        cmbLinea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(cmbLinea);
        cmbLinea.setBounds(710, 150, 210, 30);

        etProveedor2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etProveedor2.setText("Piezas:");
        pnlAnexos.add(etProveedor2);
        etProveedor2.setBounds(230, 200, 43, 15);

        etSubCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etSubCategoria.setText("Sub-Categoría:");
        pnlAnexos.add(etSubCategoria);
        etSubCategoria.setBounds(480, 130, 100, 15);

        etLinea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etLinea.setText("Línea:");
        pnlAnexos.add(etLinea);
        etLinea.setBounds(710, 130, 37, 15);

        cmbCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(cmbCategoria);
        cmbCategoria.setBounds(229, 152, 210, 30);

        cmbSubCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(cmbSubCategoria);
        cmbSubCategoria.setBounds(480, 150, 210, 30);

        etUnidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etUnidad.setText("Unidad:");
        pnlAnexos.add(etUnidad);
        etUnidad.setBounds(10, 200, 100, 15);

        cmbUnidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(cmbUnidad);
        cmbUnidad.setBounds(10, 220, 201, 30);

        etCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etCategoria.setText("Categoría:");
        pnlAnexos.add(etCategoria);
        etCategoria.setBounds(229, 131, 65, 15);
        pnlAnexos.add(jSpinner1);
        jSpinner1.setBounds(230, 220, 210, 30);
        pnlAnexos.add(spnStock);
        spnStock.setBounds(480, 220, 120, 30);

        etStock.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etStock.setText("Stock:");
        pnlAnexos.add(etStock);
        etStock.setBounds(480, 200, 39, 15);
        pnlAnexos.add(spnStockMinimo);
        spnStockMinimo.setBounds(640, 220, 120, 30);

        etStockMinimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etStockMinimo.setText("Stock Mínimo:");
        pnlAnexos.add(etStockMinimo);
        etStockMinimo.setBounds(640, 200, 90, 15);
        pnlAnexos.add(spnStockMaximo);
        spnStockMaximo.setBounds(800, 220, 120, 30);

        etStockMaximo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etStockMaximo.setText("Stock Máximo:");
        pnlAnexos.add(etStockMaximo);
        etStockMaximo.setBounds(800, 200, 90, 15);

        etCosto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etCosto.setText("Costo:");
        pnlAnexos.add(etCosto);
        etCosto.setBounds(10, 260, 40, 15);

        txtCosto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtCosto);
        txtCosto.setBounds(10, 280, 200, 30);

        txtUtilidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtUtilidad);
        txtUtilidad.setBounds(230, 280, 210, 30);

        etUtilidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etUtilidad.setText("Utilidad:");
        pnlAnexos.add(etUtilidad);
        etUtilidad.setBounds(230, 260, 90, 15);

        txtIVA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtIVA);
        txtIVA.setBounds(710, 280, 210, 30);

        etIVA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etIVA.setText("I.V.A");
        pnlAnexos.add(etIVA);
        etIVA.setBounds(710, 260, 30, 15);

        txtPrecioVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAnexos.add(txtPrecioVenta);
        txtPrecioVenta.setBounds(480, 280, 210, 30);

        etPrecioVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etPrecioVenta.setText("Precio venta:");
        pnlAnexos.add(etPrecioVenta);
        etPrecioVenta.setBounds(480, 260, 82, 15);

        btnGuardarArticulo.setBackground(new java.awt.Color(102, 255, 102));
        btnGuardarArticulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardarArticulo.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarArticulo.setText("Guardar artículo");
        pnlAnexos.add(btnGuardarArticulo);
        btnGuardarArticulo.setBounds(10, 343, 200, 30);
        pnlAnexos.add(chbIVA);
        chbIVA.setBounds(750, 250, 22, 30);

        tbpAsociados.addTab("Anexos", pnlAnexos);

        pnlAsociados.setLayout(null);

        etCodigoBarras1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etCodigoBarras1.setText("Código de barras:");
        pnlAsociados.add(etCodigoBarras1);
        etCodigoBarras1.setBounds(10, 11, 112, 15);

        txtCodigoBarras1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(txtCodigoBarras1);
        txtCodigoBarras1.setBounds(10, 30, 170, 30);

        etCodigoInterno1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etCodigoInterno1.setText("Código interno:");
        pnlAsociados.add(etCodigoInterno1);
        etCodigoInterno1.setBounds(210, 10, 96, 15);

        txtCodigoInterno1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(txtCodigoInterno1);
        txtCodigoInterno1.setBounds(210, 30, 170, 30);

        etDescripcionNormal1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etDescripcionNormal1.setText("Descripción normal:");
        pnlAsociados.add(etDescripcionNormal1);
        etDescripcionNormal1.setBounds(400, 10, 124, 15);

        txtDescripcionNormal1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(txtDescripcionNormal1);
        txtDescripcionNormal1.setBounds(400, 30, 280, 30);

        txtDescripcionCorta1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(txtDescripcionCorta1);
        txtDescripcionCorta1.setBounds(710, 30, 230, 30);

        etDescripcionCorta1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etDescripcionCorta1.setText("Descripción corta:");
        pnlAsociados.add(etDescripcionCorta1);
        etDescripcionCorta1.setBounds(710, 10, 114, 15);

        etUnidad1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etUnidad1.setText("Unidad:");
        pnlAsociados.add(etUnidad1);
        etUnidad1.setBounds(10, 80, 100, 15);

        cmbUnidad1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(cmbUnidad1);
        cmbUnidad1.setBounds(10, 100, 170, 30);

        etCosto1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etCosto1.setText("Costo:");
        pnlAsociados.add(etCosto1);
        etCosto1.setBounds(400, 80, 50, 15);

        txtCosto1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(txtCosto1);
        txtCosto1.setBounds(400, 100, 130, 30);

        etProveedor3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etProveedor3.setText("Piezas:");
        pnlAsociados.add(etProveedor3);
        etProveedor3.setBounds(210, 80, 43, 15);
        pnlAsociados.add(jSpinner2);
        jSpinner2.setBounds(210, 100, 170, 30);

        etUtilidad1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etUtilidad1.setText("Utilidad:");
        pnlAsociados.add(etUtilidad1);
        etUtilidad1.setBounds(550, 80, 90, 15);

        txtUtilidad1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(txtUtilidad1);
        txtUtilidad1.setBounds(550, 100, 130, 30);

        etPrecioVenta1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etPrecioVenta1.setText("Precio venta:");
        pnlAsociados.add(etPrecioVenta1);
        etPrecioVenta1.setBounds(710, 80, 82, 15);

        txtPrecioVenta1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAsociados.add(txtPrecioVenta1);
        txtPrecioVenta1.setBounds(710, 100, 130, 30);

        btnGuardarArticulo1.setBackground(new java.awt.Color(102, 255, 102));
        btnGuardarArticulo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardarArticulo1.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarArticulo1.setText("Guardar");
        pnlAsociados.add(btnGuardarArticulo1);
        btnGuardarArticulo1.setBounds(850, 100, 90, 30);

        tblArticulosDesign.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.white));
        jScrollPane1.setViewportView(tblArticulosDesign);

        pnlAsociados.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 930, 210);

        tbpAsociados.addTab("Asociados", pnlAsociados);

        etTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        etTitulo.setText("Administración de artículos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(etTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tbpAsociados, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(etTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addComponent(tbpAsociados, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(995, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarArticulo;
    private javax.swing.JButton btnGuardarArticulo1;
    private javax.swing.JCheckBox chbIVA;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JComboBox cmbDepartamento;
    private javax.swing.JComboBox cmbLinea;
    private javax.swing.JComboBox cmbProveedor;
    private javax.swing.JComboBox cmbSubCategoria;
    private javax.swing.JComboBox cmbUnidad;
    private javax.swing.JComboBox cmbUnidad1;
    private javax.swing.JLabel etCategoria;
    private javax.swing.JLabel etCodigoBarras;
    private javax.swing.JLabel etCodigoBarras1;
    private javax.swing.JLabel etCodigoInterno;
    private javax.swing.JLabel etCodigoInterno1;
    private javax.swing.JLabel etCosto;
    private javax.swing.JLabel etCosto1;
    private javax.swing.JLabel etDepartamento;
    private javax.swing.JLabel etDescripcionCorta;
    private javax.swing.JLabel etDescripcionCorta1;
    private javax.swing.JLabel etDescripcionNormal;
    private javax.swing.JLabel etDescripcionNormal1;
    private javax.swing.JLabel etIVA;
    private javax.swing.JLabel etLinea;
    private javax.swing.JLabel etPrecioVenta;
    private javax.swing.JLabel etPrecioVenta1;
    private javax.swing.JLabel etProveedor;
    private javax.swing.JLabel etProveedor2;
    private javax.swing.JLabel etProveedor3;
    private javax.swing.JLabel etStock;
    private javax.swing.JLabel etStockMaximo;
    private javax.swing.JLabel etStockMinimo;
    private javax.swing.JLabel etSubCategoria;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JLabel etUnidad;
    private javax.swing.JLabel etUnidad1;
    private javax.swing.JLabel etUtilidad;
    private javax.swing.JLabel etUtilidad1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JPanel pnlAnexos;
    private javax.swing.JPanel pnlAsociados;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JSpinner spnStockMaximo;
    private javax.swing.JSpinner spnStockMinimo;
    private javax.swing.JTable tblArticulosDesign;
    private javax.swing.JTabbedPane tbpAsociados;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtCodigoBarras1;
    private javax.swing.JTextField txtCodigoInterno;
    private javax.swing.JTextField txtCodigoInterno1;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtCosto1;
    private javax.swing.JTextField txtDescripcionCorta;
    private javax.swing.JTextField txtDescripcionCorta1;
    private javax.swing.JTextField txtDescripcionNormal;
    private javax.swing.JTextField txtDescripcionNormal1;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtPrecioVenta1;
    private javax.swing.JTextField txtUtilidad;
    private javax.swing.JTextField txtUtilidad1;
    // End of variables declaration//GEN-END:variables
}
